name: Bug report
description: Report a problem with flamegpu2
title: "[Bug]: "
labels: ["triage required"]
body:
  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder:
    validations:
      required: true
  - type: textarea
    id: to-reproduce
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behaviour. If applicable, provide a small reproducible code example.
      placeholder: | 
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: textarea
    id: expected-behaviour
    attributes:
      label: Expected Behaviour
      description: A clear and concise description of what you expected to happen.
      placeholder:
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Configuration (please complete the following information):
  - type: input
    id: configuration-golden
    attributes:
      label: Golden Version
      description: Golden release or commit hash
      placeholder: e.g. 1.0, d28ca67
    validations:
      required: false
  - type: input
    id: configuration-r
    attributes:
      label: R Version
      description: R release or nightly/pre-release tag
      placeholder: e.g. R 4.5.1, R-devel_2026-01-06_r89280 (nightly/pre-release)
    validations:
      required: false
  - type: input
    id: configuration-os
    attributes:
      label: Operating System
      description: Operating system type and version
      placeholder: e.g. Ubuntu 22.04, Windows 11
    validations:
      required: false
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Information
      description: Add any other context about the problem here.
      placeholder:
    validations:
      required: false