# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Create a new cohort
#'
#' Temporary testing method, probably replaced in future with R's simdata package or similar
#'
#' @param demog 
#' @param N 
#' @return A sample population data.table
create_cohort <- function(demog, N) {
    .Call(`_golden_create_cohort`, demog, N)
}

#' Execute a patient trajectory simulation
#'
#' @param initPop data.table containing initial population for simulation
#' @param parameters Simulation configuration
#' @return An list containing final population, history and timing data.tables
run_simulation <- function(initPop, parameters) {
    .Call(`_golden_run_simulation`, initPop, parameters)
}

