# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

create_cohort <- function(demog, N) {
    .Call(`_eldoradosim_create_cohort`, demog, N)
}

run_simulation <- function(initPop, parms) {
    .Call(`_eldoradosim_run_simulation`, initPop, parms)
}

