# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

is_odd <- function(d) {
    .Call(`_eldoradosim_is_odd`, d)
}

is_odd_vector <- function(x) {
    .Call(`_eldoradosim_is_odd_vector`, x)
}

run_simulation <- function(initPop, parms) {
    .Call(`_eldoradosim_run_simulation`, initPop, parms)
}

